#!/bin/bash
#
# Runs when dpkg --remove makeswap-on-azure.service is called
# Removes configuration file and swap file, if present
readonly DEPRECATED_DIR_A='/var/local/makeswap-on-azure'
readonly DEPRECATED_DIR_B='/usr/local/etc/makeswap-on-azure'
readonly SWAP_FILE='/mnt/pagefile'
readonly PARAMETER_FILE_DIR='/etc/makeswap-on-azure'

# Usage: logger "This will be logged."
logger() {
    logger "$*" >&1
}

if [ -f $SWAP_FILE ]; then
    swapoff $SWAP_FILE
    if (($? == 0)); then
        logger "Swap file disabled."
    else
        logger "Failed to disable swap file."
    fi

    rm $SWAP_FILE
    if (($? == 0)); then
        logger "Swap file removed."
    else
        logger "Failed to remove swap file."
    fi
fi

if [ -d $PARAMETER_FILE_DIR ]; then
    rm -rf $PARAMETER_FILE_DIR
    if (($? == 0)); then
        logger "Parameter file directory removed."
    else
        logger "Failed to remove parameter file directory."
    fi
fi

if [ -d $DEPRECATED_DIR_A ]; then
    rm -rf $DEPRECATED_DIR_A
    if (($? == 0)); then
        logger "Oringal parameter file directory removed."
    else
        logger "Failed to remove original parameter file directory."
    fi
fi

if [ -d $DEPRECATED_DIR_B ]; then
    rm -rf $DEPRECATED_DIR_B
    if (($? == 0)); then
        logger "Former parameter file directory removed."
    else
        logger "Failed to remove former parameter file directory."
    fi
fi