name: Deploy/Remove Tests (ubuntu-20.04)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        required-value:
          description: "required value"
          required: true
        optional-value:
          description: "optional value"
          required: false
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: github events req
        run: echo ${{ github.event.inputs.required-value }}
      - name: github events opt
        run: echo ${{ github.event.inputs.optional-value }}
      - name: SETX
        run: set -x
      - name: CD
        run: cd
      - name: MKD
        run: mkdir factions && mkdir ~/logs
      - name: mk artifacts dir
        run: mkdir -p ~/.github/artifacts
      - name: dir permissions
        run: chmod ug+rwx ~/.github/artifacts
      - name: CLONE
        run: git clone https://github.com/ppdac/makeswap-on-azure.service.git
      - name: BUILD
        run: dpkg-deb --build makeswap-on-azure.service
      - name: INSTALL
        run: sudo dpkg --install makeswap-on-azure.service.deb
      - name: ENABLE
        run: sudo systemctl enable makeswap-on-azure.service
      - name: DISABLE
        run: sudo systemctl disable makeswap-on-azure.service
      - name: INSTALL
        run: sudo dpkg --install makeswap-on-azure.service.deb
      - name: ENABLE
        run: sudo systemctl enable makeswap-on-azure.service
      - name: START
        run: sudo systemctl start makeswap-on-azure
      - name: JOURNALCTL1
        run: journalctl -xe --unit makeswap-on-azure --lines 20 --no-pager > ~/.github/artifacts/deploy20-04.journalctl1.log
      - name: DISABLE
        run: sudo systemctl disable makeswap-on-azure.service
      - name: REMOVE
        run: sudo dpkg --remove makeswap-on-azure.service
      - name: JOURNALCTL2
        run: journalctl -xe --no-pager > ~/.github/artifacts/deploy20-04.journalctl2.log
      - name: log to stdout
        run: journalctl -xe --unit makeswap-on-azure --no-pager
      - name: killswitch-strings
        run: wget https://raw.githubusercontent.com/soyfrien/makeswap-on-azure.service/main/.github/workflows/exception-strings
      - name: killswitch-log
        run: journalctl -xe --unit makeswap-on-azure --no-pager > killswitch.log
      - name: killswitch
        run:  count=$(grep -f exception-strings killswitch.log | wc -l); if [ $count > 0 ]; then exit 1; fi
      - uses: actions/upload-artifact@v3
        id: upload
        with:
          name: artifact20-04
          path: ~/.github/artifacts
      - name: Display structure of uploaded files
        run: ls -R
        working-directory: /home/runner/.github/artifacts
      - name: 'Echo upload path'
        run: echo ${{steps.upload.outputs.upload-path}}
